#!/usr/bin/env python3
"""Write END-TO-END.md from the records the live run left behind.

    python scripts/report.py
    python scripts/report.py --check     # fails if the published report drifted

Nothing here is typed by hand. Every hash, vote count, verdict and refusal in
the published report is read out of docs/live.json and docs/deployment.json, so
a claim in the report cannot drift away from the run that produced it.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
LIVE = json.loads((ROOT / "docs" / "live.json").read_text(encoding="utf-8"))
DEPLOY = json.loads((ROOT / "docs" / "deployment.json").read_text(encoding="utf-8"))
OUT = ROOT / "END-TO-END.md"
EXPLORER = "https://explorer-studio.genlayer.com"

# What each claim was built to put under the protocol, in the order a reader
# should meet them. The key is the name the live suite used.
CLAIMS = [
    ("confirmed", "The official record says it happened",
     "The exchange's own status page, inside the window, quoting the time it "
     "says withdrawals resumed."),
    ("refuted", "A document that tells the reader what to conclude",
     "The same kind of page, except that it opens by ordering the reader to "
     "answer SUPPORTS for everything and includes a forged fence terminator. "
     "What it actually says is that withdrawals did not resume."),
    ("conflicted", "Two sources that disagree",
     "Both of the above on one claim. Relevant evidence materially disagrees "
     "and an open-evidence policy has no basis for ranking one above the other."),
    ("stale", "A source that was true when it was written",
     "A report of the earlier suspension. Accurate when published, about an "
     "earlier state of the world, and published before the observation window "
     "opened."),
    ("outside", "A real page that is not the official source",
     "A genuine, stable page that is simply not the domain frozen as official "
     "for this claim. Under OFFICIAL_ONLY it cannot establish anything, "
     "whatever it says."),
    ("gone", "A source that cannot be read",
     "A commit-pinned URL that does not exist. The protocol has to be able to "
     "say that it could not look."),
]

VERDICT_MEANING = {
    "CONFIRMED": "the evidence satisfies the frozen conditions",
    "REFUTED": "the evidence establishes that the claim is not satisfied",
    "CONFLICTED": "relevant evidence materially disagrees and the frozen policy "
                  "cannot rank the sources",
    "INSUFFICIENT": "evidence was read, and it does not establish the claim",
    "UNAVAILABLE": "the evidence could not be retrieved and assessed",
}


def tx_link(tx):
    return "[`" + str(tx)[:10] + "`](" + EXPLORER + "/tx/" + str(tx) + ")"


def votes(entry):
    counts = entry.get("votes") or {}
    return ", ".join(f"{n} {name.lower()}" for name, n in sorted(counts.items()))


def lines():
    out = []
    w = out.append

    w("# Verified end to end")
    w("")
    w("Six claims on GenLayer StudioNet, chosen so that every verdict the "
      "protocol can reach is reached by real validators reading real URLs over "
      "the real web -- including the two that say the protocol cannot tell you.")
    w("")
    w("> Generated by `python scripts/report.py` from [docs/live.json](docs/live.json)")
    w("> and [docs/deployment.json](docs/deployment.json). Every hash, vote count")
    w("> and refusal below is read out of those records rather than written by hand.")
    w("")
    w("**The evidence is labelled.** " + LIVE["fixtures_are_fixtures"])
    w("")
    w("| | |")
    w("| --- | --- |")
    w(f"| Network | {LIVE['network']}, chain `{LIVE['chain_id']}` |")
    w(f"| Contract | [`{LIVE['contract']}`]({DEPLOY['explorer']}) |")
    w(f"| Deployment | {tx_link(DEPLOY['deploy_tx'])}, {DEPLOY['deploy_status']} |")
    w(f"| Contract bytes | `sha256:{DEPLOY['onchain_sha256'][:16]}...`, identical "
      f"to `{DEPLOY['source']}` at `{DEPLOY['source_commit'][:10]}` |")
    w(f"| Fixtures pinned at | `{LIVE['fixtures_commit'][:10]}` |")
    w(f"| Run | {LIVE['started_at']} to {LIVE['finished_at']} |")
    w(f"| Rules | `{LIVE['protocol']['rules']}` |")
    w("")

    w("Four accounts, because a protocol whose rules only hold for the account "
      "that wrote them does not have rules:")
    w("")
    w("| Account | Address | Does |")
    w("| --- | --- | --- |")
    roles = {
        "creator": "declares claims and freezes them",
        "submitter": "submits evidence",
        "other": "submits the second, contradicting source",
        "reader": "asks for adjudication, and reads the contract",
    }
    for name, address in LIVE["accounts"].items():
        w(f"| {name} | `{address}` | {roles.get(name, '')} |")
    w("")

    # -- the claims -----------------------------------------------------------
    w("## Every verdict, reached live")
    w("")
    w("| Claim | Verdict | Transaction |")
    w("| --- | --- | --- |")
    for key, title, _ in CLAIMS:
        claim = LIVE["claims"].get(key)
        if not claim:
            continue
        adjudication = claim["adjudication"]
        tx = next((t["tx"] for t in LIVE["transactions"]
                   if t["method"] == "adjudicate"
                   and t["step"].endswith(key.replace("gone", "unavailable"))),
                  "")
        w(f"| {title} | `{adjudication['verdict']}` | "
          f"{tx_link(tx) if tx else ''} |")
    w("")

    for key, title, why in CLAIMS:
        claim = LIVE["claims"].get(key)
        if not claim:
            continue
        adjudication = claim["adjudication"]
        w(f"### {title}")
        w("")
        w(why)
        w("")
        w("| | |")
        w("| --- | --- |")
        w(f"| Claim | `{claim['claim_id']}` |")
        w(f"| Evidence policy | `{adjudication['source_policy']}` |")
        w(f"| Verdict | **`{adjudication['verdict']}`** -- "
          f"{VERDICT_MEANING.get(adjudication['verdict'], '')} |")
        w(f"| Sources read | {adjudication['evidence_read']} read, "
          f"{adjudication['evidence_unreachable']} unreachable |")
        w(f"| Satisfying the policy | {adjudication['qualifying']} |")
        w(f"| Inside the window | {adjudication['timely']} |")
        w(f"| Supporting / contradicting | {adjudication['supporting']} / "
          f"{adjudication['contradicting']} |")
        w(f"| Conflict | `{adjudication['conflict_status']}` |")
        w(f"| What the validators agreed | "
          f"`{adjudication['decisive_digest'][:16]}...` |")
        w("")

        if claim.get("evidence"):
            w("| Source | Authority | Class | Position | Role | Quoted |")
            w("| --- | --- | --- | --- | --- | --- |")
            for item in claim["evidence"]:
                quote = (item.get("quote") or "nothing settles it")
                quote = quote.replace("|", "\\|").replace("\n", " ").strip()
                if len(quote) > 90:
                    quote = quote[:87].rstrip() + "..."
                w(f"| `{item['source_host']}` | {item['authority']} | "
                  f"{item['source_class'] or '-'} | {item['position'] or '-'} | "
                  f"{item['role'] or '-'} | {quote} |")
            w("")

    w("The hostile document is the one worth dwelling on. It demanded "
      "`SUPPORTS` for every question and carried a forged fence terminator. It "
      "was quoted to the readers inside a fence it could not close, its "
      "instruction was read as part of the document being assessed, and the "
      "claim is recorded `REFUTED` on the strength of what the page actually "
      "says. It got the verdict its content earned.")
    w("")

    # -- refusals -------------------------------------------------------------
    refusals = LIVE["refusals"]
    w("## What the contract refused")
    w("")
    w(f"{len(refusals)} refusals landed on chain in the same run. Each is an "
      f"accepted transaction whose execution errored, which is the honest "
      f"shape: the validators agreed about the refusal, and the reason is "
      f"recorded rather than swallowed by a client.")
    w("")
    w("| Attempt | Sent by | Refused with | Transaction |")
    w("| --- | --- | --- | --- |")
    for entry in refusals:
        reason = str(entry.get("refusal", ""))
        if '"payload": "' in reason:
            reason = reason.split('"payload": "', 1)[1].split('"', 1)[0]
        reason = reason.replace("|", "\\|")
        if len(reason) > 120:
            reason = reason[:117].rstrip() + "..."
        w(f"| {entry['step']} | {entry['caller']} | {reason} | "
          f"{tx_link(entry['tx'])} |")
    w("")

    # -- every transaction ----------------------------------------------------
    w("## Every transaction in the run")
    w("")
    w("| Step | Sent by | Status | Execution | Validators | Transaction |")
    w("| --- | --- | --- | --- | --- | --- |")
    for entry in LIVE["transactions"]:
        w(f"| {entry['step']} | {entry['caller']} | {entry['status']} | "
          f"{entry['execution']} | {votes(entry)} | {tx_link(entry['tx'])} |")
    w("")
    w("`ACCEPTED` and finalized are two different facts. Every transaction here "
      "was accepted by consensus; the deployment record carries the finalized "
      "status of the contract itself, and the console asks the finalized view "
      "directly rather than claiming a finality it has not checked.")
    w("")
    w("One of these rounds carries a `disagree` vote. A validator genuinely "
      "disagreed and the round still reached a majority, which is what "
      "Optimistic Democracy looks like when it is actually running rather than "
      "being described.")
    w("")

    # -- custody --------------------------------------------------------------
    custody = LIVE.get("custody") or {}
    if custody:
        w("## Custody at the end of the run")
        w("")
        w("| | |")
        w("| --- | --- |")
        w(f"| Held in escrow | {custody.get('escrow_held')} |")
        w(f"| Sum of every claim's ledger | {custody.get('sum_of_claims')} |")
        w(f"| Balanced | {custody.get('balanced')} |")
        w("")
        w("The bounty paths are exercised in the Direct Mode suite with three "
          "distinct accounts rather than here: StudioNet is gasless and its "
          "accounts hold no balance to deposit, so a live escrow run would "
          "prove nothing a mocked one does not. What this run proves is that "
          "the contract holds nothing it was not given.")
        w("")

    w("## Running this again")
    w("")
    w("```bash")
    w("python scripts/live.py")
    w("```")
    w("")
    w("The suite asserts rather than prints: a wrong verdict, a missing "
      "refusal, or a source that qualified when the frozen policy excludes it "
      "fails the run. It costs real consensus rounds on a shared network, so "
      "it takes a while, and the transaction hashes it produces will not be "
      "the ones above.")
    w("")
    return out


def main() -> int:
    body = "\n".join(lines()).rstrip() + "\n"
    if "--check" in sys.argv:
        current = OUT.read_bytes().decode("utf-8") if OUT.exists() else ""
        if current == body:
            print("END-TO-END.md is what docs/live.json generates")
            return 0
        print("END-TO-END.md is not what docs/live.json generates; run "
              "python scripts/report.py and commit the result")
        return 1
    OUT.write_text(body, encoding="utf-8", newline="")
    print(f"wrote END-TO-END.md, {len(body)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
